# Generated by Django 3.1.4 on 2022-06-17 08:03

import common.serializers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import house.models
import house.storages_backend
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=225)),
                ('request_status', models.CharField(choices=[('1', 'Accept'), ('2', 'Reject'), ('3', 'Pending')], default='3', max_length=20)),
                ('address', models.CharField(max_length=255)),
                ('number_of_floor', models.PositiveIntegerField()),
                ('area', models.FloatField()),
                ('full_address', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True, max_length=1023)),
                ('main_image', models.JSONField(blank=True, default=list, encoder=common.serializers.ImageEncoder)),
                ('detail_images', models.JSONField(blank=True, default=list, encoder=common.serializers.ImageEncoder)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='common.city')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='common.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='houses', to='common.ward')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('main_image', models.BooleanField(default=False)),
                ('image', models.ImageField(storage=house.storages_backend.HouseImageStorage, upload_to=house.models.house_image_upload_dir)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_images', to='house.house')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
